<div style="text-align: center;">
<h2>INFSCI 2915 Foundations- Machine Learning - Spring 2018 </h2>
<h1 style="font-size: 250%;">Assignment #3</h1>
<h3>Issued Monday, 3/26/2018; Due Monday, 11:59pm, 4/09/2018</h3>
<h3>Total points: 100 </h3>
</div>

In [35]:
# Type in your information in the double quotes
firstName = "Echhit"
lastName = "Joshi"
pittID = "EBJ7@pitt.edu"

<h3>  Problem #1.Linear Discriminant Analysis (LDA)and Quadratic Discriminant Analysis(QDA)      <br>[30 points]</h3> 
 Writing a code is not required for this problem.

<h4> Problem #1-1</h4>  <br>
Assume we have K classes to be classified with one feature $(x)$. The prior probability of
class $k$ is $𝜋_{k} = 𝑃(𝑌 = 𝑘)$. Assume that the feature in class k has Gaussian distribution of
mean $μ_{k}$ and variance $σ^2 (𝒩(μ,𝜎^{2}))$.The variance is the same for all classes. 
Prove that the Bayes’ classifier (that chooses class k with largest $𝑃(𝑌 = 𝑘|𝑥))$ is equivalent to assigning an observation to the class for which the discriminant function $𝛿_{k}(x)$ is
maximized, where 
\begin{array} \\
𝛿_{k}(x) = x\frac{\mu _{k}}{\sigma ^{2}}- \frac{\mu_{2}^{k}}{2\sigma ^{2}}+ log(\pi _{k})
\end{array}
<br> What is the name of this classifier?


# ANSWER(REFER ATTACHED PICTURE FOR PROOF)
    
    The name of the Classifier is the Bayes Classifier.


<h4> Problem #1-2</h4>  <br>
Extend **Problem #1-1** to include **p** features. With features from each class drawn from a
Gaussian distribution with mean vector $μ_{k}$ and covariance matrix $Σ_{k}$ (which is now
different for each class). Find the discriminant function that maximizes **𝑃(𝑌 = 𝑘|𝑥)**. Is
the relationship with the feature vector **x** linear?<br> What is this classifier?


# ANSWER(REFER ATTACHED PICTURE FOR PROOF)


<h4> Problem #1-3</h4>  <br>
- Explain Bias-variance trade-off in choosing between LDA and QDA

# ANSWER:

    LDA is the simpler model between the two. It might have high bias as it is less complex compared to QDA. Since it only has 1 class to predict, It just needs to estimate a single covariance matrix. For QDA, covariance matrix is estimated for each class. Each matrix has (p*(p+1))/2 parameters. This makes QDA very complex and therefore there might be a problem of overfitting if the training dataset is small.

<h3>  Problem #2. Support Vector Machines  [20 points]</h3> 
Writing a code is not required for this problem.

<h4> Problem #2-1 Answer the following quesionts </h4> 

- Describe limitations of using Maximal Margin Classifier 
- What is the difference between Support Vector Classifier and Maximal Margin Classifier
- Explain Bias-variance trade-off that occurs when we choose large and small values for the Slack Variables


# ANSWER

1) The Maximal Margin Classifier is very sensitive to the training set that it is derived from. A small change in the training data could result in drastically different Margin which may not perform very well on the test data. Another limitation is that the data may actually not be seperable using a Maximal Margin Classifier and therefore the classifier might result in high errors.

2) The main difference between Support Vector Classifier and Maximal Margin Classifier is that Maximal Margin Classifier is a fixed boundary and does not account for points that are on the wrong side of the boundary. Support Vector Classifier uses slack variables to determine training points that are on the wrong side of the decision boundary and accounts for the positions of the data points within a range of the wrong side of the decision boundary.

3) When Slack Variables are large, the Classifier is more tolerable to violation by the points being on the wrong side of the boundary. This in term creates a large margin and therefore there is high bias, with low variance. Conversely, when Slack Variables are small, the Classifier is more strict and does not tolerate as much violation. This could result in overfitting and the Classifier only performs well on the training data. This creates a high variance with low bias.

<h4> Problem #2-2</h4><br>
How does the Radial Basis Function Kernel in SVM measure the similarity between a test point and a training example? Discuss the impact of choosing a large RBF parameter **𝛾**
on the learning algorithm.

# ANSWER

1) As Radial Basis Function Kernel in SVM is a Gaussian-like measure, the kernel measures the similarity between a test point and a training example by computing the squared Euclidean distance between the test and training example. 
    When a large RBF parameter 𝛾 is chosen, the spread of the distribution decreases which in turn results in a high variance and low bias. When test points are compared to the training example, it might not be able to accurate predict the test point.

<h3>  Problem #3 Classification Performance Evaluation and Cross validation [30 points]</h3> 


<h4> Problem #3-1</h4> <br>
In a fraud detection system, a QDA classifier’s confusion matrix is found to be:

|        |Predicted Class - Not fraud| Predicted Class - fraud|
|:--:|:-------------------------------:|
|Actual class – Not fraud|1000|20|
|Actual class – fraud|30|5|

- Evaluate the overall error rate and the accuracy<br>
- Evaluate the precision and the recall <br>
- Is dataset balanced?
- Comment on the results.

# ANSWER

1) Overall error rate = (total error)/(total observations) = (30+20)/1055 = 0.0474
   Accuracy of Confusion Matrix = (True Fraud + True Not Fraud)/ (total observations) = (1000+5)/1055 = 0.953
   
2) Precision = (True Fraud)/(Total Predicted Fraud) = 5/(20+5) = .2
   Recall = (True Fraud)/(Actual Fraud) = 5/(30+5) = .143

3) The dataset is not balanced as there is a skewed class. There is not enough training samples for the "Fraud" class(25) compared to the "Not Fraud" class(1030). 

4) We can see that the Accuracy is very high while there is no sufficent evidence for the "Fraud" class to be correctly predicted given the observation count. The Precision and Recall scores are very low suggesting that the dataset is skewed. The Precision is only .2 which means that only 20% of the total predicted "Fraud" is correct. While the Recall is only .143 which means that only 14.3% of datapoints were accurately detected as "Fraud".


<h4> Problem #3-2</h4> <br>
Assuming we want to lower the misclassification of fraud. How can you modify the classifier to do better classification using information from confusion matrix? 

# ANSWER

    We could modify the classifier to do better classification by significantly lowering the threshold for the "Fraud" class. Since there are only two classes, the default threshold for predicting a class given the features would be 0.5, Setting a value less than 0.5 would theoretically increase the prediction accuracy given the skewed dataset.

<h4> Problem #3-3 Cross validation, SVM </h4> <br>
In this exercise, we will use SVM  for breast cancer classification (malignant or benign).<br> 
Use a code below to download the dataset:


In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
dataset = load_breast_cancer()
print(dataset.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


Follow steps to answer questions.
- Scale the features with MinMaxScaler
- Split breast cancer dataset into two, test dataset and train dataset
- Find best SVM classifier model. Try values of C=[0.001, 0.1, 1, 10, 1000] and Gamma = [0.001, 0.1, 1, 10, 1000]. 
- Use 3-fold cross validation to find the best parameters (using all possible combinations of these values for C and gamma).
- Report your parameters
- Report accuracy, confusion matrix, precision, and recall (use Test dataset, SVM classifier model with best parameters)
- Comment your results

In [137]:
#Write your answer here
dataFrame1=pd.DataFrame(dataset.data,columns=dataset.feature_names)
scaler=preprocessing.MinMaxScaler()
scaler.fit(dataset['data'])
X_transformed=scaler.transform(dataset['data'])
X_train, X_test, Y_train, Y_test = train_test_split(X_transformed,dataset['target'],random_state=0)
dataFrame1.describe(include='all')



mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
count       569.00        569.00          569.00     569.00           569.00   
mean         14.13         19.29           91.97     654.89             0.10   
std           3.52          4.30           24.30     351.91             0.01   
min           6.98          9.71           43.79     143.50             0.05   
25%          11.70         16.17           75.17     420.30             0.09   
50%          13.37         18.84           86.24     551.10             0.10   
75%          15.78         21.80          104.10     782.70             0.11   
max          28.11         39.28          188.50    2501.00             0.16   

       mean compactness  mean concavity  mean concave points  mean symmetry  \
count            569.00          569.00               569.00         569.00   
mean               0.10            0.09                 0.05           0.18   
std                0.05            0.08                 0.04           0.03   
min                0.02            0.00                 0.00           0.11   
25%                0.06            0.03                 0.02           0.16   
50%                0.09            0.06                 0.03           0.18   
75%                0.13            0.13                 0.07           0.20   
max                0.35            0.43                 0.20           0.30   

       mean fractal dimension           ...             worst radius  \
count                  569.00           ...                   569.00   
mean                     0.06           ...                    16.27   
std                      0.01           ...                     4.83   
min                      0.05           ...                     7.93   
25%                      0.06           ...                    13.01   
50%                      0.06           ...                    14.97   
75%                      0.07           ...                    18.79   
max                      0.10           ...                    36.04   

       worst texture  worst perimeter  worst area  worst smoothness  \
count         569.00           569.00      569.00            569.00   
mean           25.68           107.26      880.58              0.13   
std             6.15            33.60      569.36              0.02   
min            12.02            50.41      185.20              0.07   
25%            21.08            84.11      515.30              0.12   
50%            25.41            97.66      686.50              0.13   
75%            29.72           125.40     1084.00              0.15   
max            49.54           251.20     4254.00              0.22   

       worst compactness  worst concavity  worst concave points  \
count             569.00           569.00                569.00   
mean                0.25             0.27                  0.11   
std                 0.16             0.21                  0.07   
min                 0.03             0.00                  0.00   
25%                 0.15             0.11                  0.06   
50%                 0.21             0.23                  0.10   
75%                 0.34             0.38                  0.16   
max                 1.06             1.25                  0.29   

       worst symmetry  worst fractal dimension  
count          569.00                   569.00  
mean             0.29                     0.08  
std              0.06                     0.02  
min              0.16                     0.06  
25%              0.25                     0.07  
50%              0.28                     0.08  
75%              0.32                     0.09  
max              0.66                     0.21  

[8 rows x 30 columns]

In [136]:
#best SVM Classifier Model:
a = [0.001, 0.1, 1, 10, 1000]
for i in a:
    svmModel=SVC(kernel='rbf', gamma=i, C=i)
    svmModel.fit(X_train,Y_train)
    print("The Accuracy when C and G are ", i ," is : ", svmModel.score(X_test,Y_test))

The Accuracy when C and G are  0.001  is :  0.629370629371
The Accuracy when C and G are  0.1  is :  0.937062937063
The Accuracy when C and G are  1  is :  0.972027972028
The Accuracy when C and G are  10  is :  0.951048951049
The Accuracy when C and G are  1000  is :  0.629370629371


In [135]:
#3 fold Cross validation to find best parameters:
for i in a:
    for x in range(0,len(a)):
        svmModel=SVC(kernel='rbf', gamma=a[x], C=i)
        svmModel.fit(X_train,Y_train)
        scores = cross_val_score(svmModel, X_train, Y_train, cv=3)
        score = np.mean(scores)
        print("The Scores using 3-fold validation when C is:",i, "and G is ", a[x] ," is : ",score)


The Scores using 3-fold validation when C is: 0.001 and G is  0.001  is :  0.62676056338
The Scores using 3-fold validation when C is: 0.001 and G is  0.1  is :  0.62676056338
The Scores using 3-fold validation when C is: 0.001 and G is  1  is :  0.62676056338
The Scores using 3-fold validation when C is: 0.001 and G is  10  is :  0.62676056338
The Scores using 3-fold validation when C is: 0.001 and G is  1000  is :  0.62676056338
The Scores using 3-fold validation when C is: 0.1 and G is  0.001  is :  0.62676056338
The Scores using 3-fold validation when C is: 0.1 and G is  0.1  is :  0.87558685446
The Scores using 3-fold validation when C is: 0.1 and G is  1  is :  0.943661971831
The Scores using 3-fold validation when C is: 0.1 and G is  10  is :  0.629107981221
The Scores using 3-fold validation when C is: 0.1 and G is  1000  is :  0.62676056338
The Scores using 3-fold validation when C is: 1 and G is  0.001  is :  0.62676056338
The Scores using 3-fold validation when C is: 1 and G

# ANSWER

    The best parameters using the 3-fold Cross Validation are (C=1,G=1), (C=10,G=0.1), or (C=10,G=1)
   

<h4> Problem #3-4 Cross validation, Logistic regression </h4>

- Repeat **Problem #3-3** but instead of SVM find best Logistic regression classifier model. Try values of C= [0.001,0.01,1,10,100, 1000] and Penalty = ["l1","l2"]


In [152]:
#Using Logistic Regression Classifier Model Instead of SVM
#Second Split for seperating Validation Set:
X_trainV, X_testV, Y_trainV, Y_testV = train_test_split(X_train,Y_train,random_state=0)
b = ['l1','l2']
best_score = 0
for x in range(0,1):
    penalty = b[x]
    for i in a:
        logRegModel = LogisticRegression(penalty=penalty,C=i).fit(X_trainV,Y_trainV)
        score1 = logRegModel.score(X_testV,Y_testV)
        if score1>best_score:
            best_score = score1
            best_parameter = i
NewlogRegModel = LogisticRegression(C=best_parameters).fit(X_train,Y_train)
test_score = NewlogRegModel.score(X_test,Y_test)
print("The best score on the validation is: ",best_score)
print("The best parameter on the validation is: ",best_parameter)
print("The test score with best Parameters is: ",test_score)

The best score on the validation is:  0.981308411215
The best parameter on the validation is:  10
The test score with best Parameters is:  0.965034965035


<h3>  Problem #4  Neural Networks [20 points]</h3> 
In this exercise we will clasify Iris species (Setosa, Versicolor, Virginica) using Neural Networks.<br>
Use a code below to download the dataset:

In [7]:
from sklearn.datasets import load_iris
from sklearn.neural_network import MLPClassifier 
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import confusion_matrix, precision_score, recall_score
dataset2=load_iris()
print(dataset2.keys())

dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names'])


Follow steps to answer questions.
- Scale the feautures with MinMaxScaler, then use sklearn MLPClassifier. 
- Build a model that has two hidden layers, the first layer has 10 neurons and second layer has 5 neurons. 
- Use 'relu' activation function, and set the regularization parameter alpha=0.5. 
- Set the random_state=0 for splitting and building all models.


<h4> Problem #4-1 </h4>
- Use gradient descent to solve the optimization  problem (i.e. get the weights), and choose random_state=0 (which corresponds to a particular initializationo of weight values). 
- Report accuracy, confusion matrix, precision, and recall 

In [9]:
#Scaling features and then solving the optimization problem using gradient descent(Optimization only converged with max iteration of 3000)
scaler=preprocessing.MinMaxScaler()
scaler.fit(dataset2['data'])
X_train_scaled = scaler.transform(dataset2['data'])
X_train, X_test, Y_train, Y_test = train_test_split(X_train_scaled,dataset2['target'],random_state=0)
MLPmodel=MLPClassifier(solver = 'sgd', activation = 'relu', random_state = 0,max_iter=3000, hidden_layer_sizes=[10,5], alpha = 0.5)
MLPmodel.fit(X_train,Y_train)

#Accuracy, Confusion Matrix, Precision, and Recall
print("The Accuracy of the MLP Classifier is: ", MLPmodel.score(X_test,Y_test))
PredictedOutput=MLPmodel.predict(X_test)
confusion=confusion_matrix(Y_test,PredictedOutput)
print("The Confusion Matrix is: \n",confusion)
print("The Precision score for MLP model is: ", precision_score(Y_test,PredictedOutput,average='macro'))
print("The Recall score for MLP model is: ", recall_score(Y_test,PredictedOutput,average='macro'))

The Accuracy of the MLP Classifier is:  0.973684210526
The Confusion Matrix is: 
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
The Precision score for MLP model is:  0.966666666667
The Recall score for MLP model is:  0.979166666667


<h4> Problem #4-2 </h4>
- Repeat **Problem #4-1** but with a model that use random_state=10 to initialize the weights. 
- Report accuracy, confusion matrix, precision, and recall

In [5]:
#Initializing the weight by setting random_state to 10
MLPmodel2=MLPClassifier(solver = 'sgd', activation = 'relu', random_state = 10,max_iter=3000, hidden_layer_sizes=[10,5], alpha = 0.5)
MLPmodel2.fit(X_train,Y_train)

#Accuracy, Confusion Matrix, Precision, and Recall
print("The Accuracy of the MLP Classifier is: ", MLPmodel2.score(X_test,Y_test))
PredictedOutput=MLPmodel.predict(X_test)
confusion=confusion_matrix(Y_test,PredictedOutput)
print("The Confusion Matrix is: \n",confusion)
print("The Precision score for MLP model is: ", precision_score(Y_test,PredictedOutput,average='macro'))
print("The Recall score for MLP model is: ", recall_score(Y_test,PredictedOutput,average='macro'))

The Accuracy of the MLP Classifier is:  0.947368421053
The Confusion Matrix is: 
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
The Precision score for MLP model is:  0.966666666667
The Recall score for MLP model is:  0.979166666667


<h4> Problem #4-3 </h4>
- Repeat **Problem #4-2** but with model that use L-BFGS (a numerical quasi-Newton method) instead of stochastic gradient descent to find the weights.
- Report accuracy, confusion matrix, precision, and recall
- Comment on results

In [6]:
#Using L-BFGS(quasi Newton Method) to find the weights
MLPmodel3=MLPClassifier(solver = 'lbfgs', activation = 'relu', random_state = 0, hidden_layer_sizes=[10,5], alpha = 0.5)
MLPmodel3.fit(X_train,Y_train)

#Accuracy, Confusion Matrix, Precision, and Recall
print("The Accuracy of the MLP Classifier is: ", MLPmodel3.score(X_test,Y_test))
PredictedOutput=MLPmodel.predict(X_test)
confusion=confusion_matrix(Y_test,PredictedOutput)
print("The Confusion Matrix is: \n",confusion)
print("The Precision score for MLP model is: ", precision_score(Y_test,PredictedOutput,average='macro'))
print("The Recall score for MLP model is: ", recall_score(Y_test,PredictedOutput,average='macro'))

The Accuracy of the MLP Classifier is:  0.973684210526
The Confusion Matrix is: 
 [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
The Precision score for MLP model is:  0.966666666667
The Recall score for MLP model is:  0.979166666667


# ANSWER

    The L-BFGS had a higher accuracy compared to Stochastic gradient descent. The Gradient descent model failed to converge and therefore the max iterations had to be increased. Increasing the random state or initializing the weights actually resulted in a lower accuracy among the gradient descent algorithms.
    
    The L-BFGS model had a better prediction accuracy. This suggests that the dataset is small and therefore it predicted better than the Gradient Descent. The Precision and Recall scores for both L-BFGS and Stochastic Gradient Descent were high and equal. This suggests that the data is not skewed and is accurately predicted by both the algorithms.